### ISSUE TITLE
Windows | Git Bash | activator run results in IllegalArgumentException: URI has an authority component

### ISSUE THREAD

**Issue by StephenMP** [typesafehub/activator#1033]
My apologies if this issue already exists, I couldn't find one that was open related to this.

**Description:**
When trying to run a new project created from activator from the Git Bash terminal, an IllegalArgumentException occurs.

**OS:** Windows 8.1
**Terminal:** Git Bash 1.9.4

**Steps to Reproduce:**
* Type: activator new
* Choose play-scala
* Enter project name
* Switch to new project directory
* Type: activator run

**Exception Output:**
```
java.lang.IllegalArgumentException: URI has an authority component
        at java.io.File.<init>(Unknown Source)
        at sbt.Classpaths$.sbt$Classpaths$$bootRepository(Defaults.scala:1758)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1729)
        at sbt.Classpaths$$anonfun$appRepositories$1.apply(Defaults.scala:1729)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLik
.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLik
.scala:244)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimiz
d.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244
$
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Classpaths$.appRepositories(Defaults.scala:1729)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1102)
        at sbt.Classpaths$$anonfun$41.apply(Defaults.scala:1102)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1
apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by keepscoding** [comment]
+1

**Comment by doron123** [comment]
+1

**Comment by jhuenges** [comment]
+1

**Comment by apompa** [comment]
+1

**Comment by grupp3pvt15** [comment]
+1 Same thing with play-Java for me

**Comment by albuch** [comment]
See temporary workaround mentioned at https://github.com/sbt/sbt/issues/2044

**Comment by keepscoding** [comment]
Try to close console and delete all the contents in the C:\Users\<name>\.sbt\*.*
Mine worked after delete...

**Comment by jfuentescpp** [comment]
@keepscoding solution works for me. 
"Try to close console and delete all the contents in the C:\Users<name>.sbt*.*"

I got this issue when update to 1.3.4 activator version maybe some incompatible files were already in me PC. 

play-fork-run.sbt is still in 
addSbtPlugin("com.typesafe.play" % "sbt-fork-run-plugin" % "2.3.9")

**Comment by dgiesy** [comment]
Has anyone found a way to prevent the repositories file from being overwritten again on every startup? It is a pain having to add the third "/" every time you want to restart the app.

**Comment by keepscoding** [comment]
@jfuentescpp I'm sorry i didn't realize the path not display correctly. 
It should work if you delete the content inside .sbt folder.

**Comment by keepscoding** [comment]
you can use cygwin instead

**Comment by darwyn00** [comment]
Not sure when this defect was introduced into Activator. But here's a link to a related StackOverflow conversation: http://stackoverflow.com/questions/30624099/sbt-0-13-8-uri-has-an-authority-component

**Comment by mprentic-harris** [comment]
Deleting `~/.sbt/` did not work for me on Windows 7 with Play 2.4.2 and activator 1.3.2. I also did not have a `~/.sbt/repositories` file. But after deleting `~/.sbt/` and running activator, I received the same exception,but it created the `~/.sbt/repositories` file. Changing the local URLs from `file://` to `file:///` resolved the error and let me finally run my projects with activator and SBT 0.13.8.

**Comment by keepscoding** [comment]
+1

**Comment by julrod092** [comment]
+1

**Comment by Segamo** [comment]
+1

**Comment by PhilAndrew** [comment]
Every single DAY I have to edit the repositories file and insert more forward slashes from file:// to file:/// - EVERY DAY. EVERY DAY. EVERY DAY.

**Comment by cpoliwoda** [comment]
I tried the activator 1.3.5 with the akka project/tutorial on Windows 7 and already modified both file:/// in .sbt/repositories but still have the same behaviour.

**Comment by mdclark01** [comment]
+1

**Comment by renejahn** [comment]
+1

**Comment by azhidkov** [comment]
+1

**Comment by LogicalTime** [comment]
+1

**Comment by Madder** [comment]
+1

**Comment by tiernanscully** [comment]
+1

**Comment by Scully17** [comment]
+1

**Comment by keepscoding** [comment]
https://groups.google.com/d/msg/play-framework/aAXQeFlzXU8/EP0cAPr1H4EJ

**Comment by awronski** [comment]
+1

**Comment by oleg-gr** [comment]
+1

**Comment by kennandavison** [comment]
http://puu.sh/jrwXm/90bab27c2a.png

Any reason that my repositories folder isn't showing up? I've deleted the .sbt server and run activator ui in git bash, but it doesn't seem to be generating.

**Comment by daalwr** [comment]
+1

**Comment by veita** [comment]
The problem persists in 1.3.5.

**Comment by halfabench** [comment]
+1

**Comment by Konnor95** [comment]
+1

**Comment by PhilAndrew** [comment]
My solution is as follows:

    package fixit
    
    import java.time.LocalDate
    
    import scala.io.Source
    
    object Fixit {
    
      def main(args:Array[String]) = {
    
    
        val repo = "C:\\Users\\user\\.sbt\\repositories"
        while (true) {
          var changed = false
    
          Thread.sleep(5000)
          val linesIn = Source
            .fromFile(repo)
            .getLines.toList
    
          val linesOut = linesIn
            .map { line => {
    
              if (line.indexOf("file://$") >= 0)
                changed = true
    
              line.replace("file://$", "file:///$")
            }
            }
    
          if (changed) {
            println("Stupid repo file changed " + LocalDate.now().toString)
            import java.nio.file.{Paths, Files}
            import java.nio.charset.StandardCharsets
    
            Files.write(Paths.get(repo), linesOut.mkString("\n").getBytes(StandardCharsets.UTF_8))
          }
        }
      }
    }

**Comment by wcmjunior** [comment]
+1

**Comment by aleksandarbosancic** [comment]
+1

**Comment by sydar314** [comment]
+1

**Comment by Madder** [comment]
+1

**Comment by corruptmemory** [comment]
Activator 1.3.6 is out and should address this issue.  Please confirm.

**Comment by felix-schwarz** [comment]
My system just updated from 1.3.5 to 1.3.6 - and now I have this problem, too (I didn't have it before).

**Comment by corruptmemory** [comment]
@felix-schwarz, thanks for the detail.  Could you run an experiment for me please:

1. Run 1.3.6
2. Open a project
3. Let everything fail as you noticed
4. Please report the contents of your `~/.sbt/repositories`
5. Also, please supply info on your version of Windows and Java.

Another question: are you running from Cygwin or other Unix-like shell or from the regular Windows command shell?  If you're using something other than the regular Windows command shell try it with the command shell and see if it works.

Thanks.  And sorry for the troubles.  I'll look into what I can do for the next bugfix release.

You might also want to try 1.3.6 but first delete the content of `~/.sbt/repositories`.

**Comment by felix-schwarz** [comment]
This should be the content of ~/.sbt/repositories that I saved prior to switching from 1.3.6 back to 1.3.5:

-- begin --
[repositories]
  local
  activator-launcher-local: file://${activator.local.repository-${activator.home-${user.home}/.activator}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  activator-local: file://${activator.local.repository-/Applications/activator-dist-1.3.5/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central
  typesafe-releases: http://repo.typesafe.com/typesafe/releases
  typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
-- end --

I'm running OS X 10.11 (latest developer preview) and - afaik - the latest Java release:

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

If I find a little time, I'll try the dist-version of 1.3.6 (rather than the auto-updated-to-1.3.6 dist-version of 1.3.5) tomorrow.

**Comment by corruptmemory** [comment]
Um, woah?

The fix in 1.3.6 does not apply to anything other than Windows.  So, um, this appears to be a new problem.

**Comment by felix-schwarz** [comment]
I have good news for you, though: using the dist-version of 1.3.6 rather than the dist-version of 1.3.5 + auto-update to 1.3.6, everything works fine. Happily running 1.3.6 now.

**Comment by mendrik** [comment]
+1!

**Comment by JanosKranczlerEpam** [comment]
+1

**Comment by Linowitch** [comment]
+1

**Comment by corruptmemory** [comment]
Hrm.  This issue should be addressed.  Versions of sbt and activator people are using?

**Comment by Linowitch** [comment]
OS -> Win 7 Professional 64Bit
Git Bash -> 1.9.5 / 2.7.0

sbt -> 0.13.5 / 0.13.7
activator -> 1.2.12 / 1.3.7

**Comment by Linowitch** [comment]
activator -> 1.3.10

issue still there.

**Comment by ehartford** [comment]
I have this error too

**Comment by kevinhaas** [comment]
Works fine in cygwin on Win10 Anniversary, just not GitBash.

**Comment by PhilAndrew** [comment]
what is cygwin? I use DOS

**Comment by kuc** [comment]
@PhilAndrew "DOS"?! Did you mean `cmd.exe`?

**Comment by PhilAndrew** [comment]
Yeah `cmd.exe`, like when I used to play with Gw-basic as a kid and format 5 1/4 floppy disks, its a nostalgic thing I can't stop doing

**Comment by ehartford** [comment]
http://www.jefflewis.net/archive/programming/gorilla.bas
hahaha

**Comment by Aphax** [comment]
I have this error too with activator 1.3.12, running on windows 7 enterprise and ConEmu terminal.
