### ISSUE TITLE
Cannot create new play-scala project, failed to load SBT configuration File

### ISSUE THREAD

**Issue by Hajtosek** [typesafehub/activator#1034]
Hi,
when i tried to create new project using play-scala seed i get "Failed to load SBT configuration file" and following output in build:

    New log file opened at Mon Jun 01 18:56:08 CEST 2015 by 6541@haito-dev
    jvm 6541@haito-dev
    jvm vmName=Java HotSpot(TM) 64-Bit Server VM vmVendor=Oracle Corporation vmVersion=25.45-b02
    jvm specName=Java Virtual Machine Specification specVendor=Oracle Corporation specVersion=1.8
    jvm arguments: [-javaagent:/usr/share/java/jayatanaag.jar, -Xms256m, -Xmx1024m]
    Starting event engine
    Starting sbt command engine
    Waiting for sbt command engine
    Command engine arguments=List()
    Command engine baseDirectory=/home/haito/IdeaProjects/Scala/pinboard
    Command engine initial remaining commands List(--initialize, onFailure load-failed, boot, server-send-ready-for-request, server-handle-next-server-request)
    > --initialize
    > initialize
    > onFailure load-failed
    > boot
    > reload
    [Loading] Scanning directory /home/haito/IdeaProjects/Scala/pinboard/project
    [Loading] Found non-root projects 
    [Loading] Done in /home/haito/IdeaProjects/Scala/pinboard/project, returning: ()
    deducing auto plugins based on known facts Set(Atom(sbt.plugins.CorePlugin)) and clauses Clauses(List(Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.JUnitXmlReportPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.CorePlugin),Set(Atom(sbt.plugins.IvyPlugin))), Clause(Atom(sbt.plugins.IvyPlugin),Set(Atom(sbt.plugins.JvmPlugin))), Clause(Atom(sbt.plugins.JvmPlugin),Set(Atom(sbt.plugins.JUnitXmlReportPlugin)))))
      :: deduced result: Matched(sbt.plugins.CorePlugin,sbt.plugins.IvyPlugin,sbt.plugins.JvmPlugin,sbt.plugins.JUnitXmlReportPlugin)
    sorting: ns: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
      :: sorting:: found: List(sbt.plugins.CorePlugin) not found List(sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
      :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin) not found List(sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
      :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin) not found List(sbt.plugins.JUnitXmlReportPlugin)
      :: sorting:: found: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin) not found List()
      :: sorted deduced result: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
    [Loading] Done in /home/haito/IdeaProjects/Scala/pinboard/project, returning: (pinboard-build)
    Loading project definition from /home/haito/IdeaProjects/Scala/pinboard/project
    Running task... Cancel: sbt.TaskCancellationStrategy$Null$@13a44e1d, check cycles: false
    
    Initial source changes: 
        removed:Set()
        added: Set()
        modified: Set()
    Removed products: Set()
    External API changes: API Changes: Set()
    Modified binary dependencies: Set()
    Initial directly invalidated sources: Set()
    
    Sources indirectly invalidated by:
        product: Set()
        binary dep: Set()
        external source: Set()
    All initially invalidated sources: Set()
    
    Copy resource mappings: 
        
    [Loading] Scanning directory /home/haito/IdeaProjects/Scala/pinboard
    [Loading] Found root project root w/ remaining 
    play/Play$
    java.lang.NoClassDefFoundError: play/Play$
    Use 'last' for the full log.
    > load-failed
    Failed to load project.
    > server-wait-for-reboot

Can anyone relate?

**Comment by Gbedeawy** [comment]
For now you'll have to not use the Activator ui, until They fix this in Activator.

A Workaround change in 'play-fork-run.sbt'
addSbtPlugin("com.typesafe.play" % "sbt-fork-run-plugin" % "2.3.8")
Change to
addSbtPlugin("com.typesafe.play" % "sbt-fork-run-plugin" % "2.4.0")

but you will have to do it every time you close Activator UI

**Comment by Hajtosek** [comment]
@Gbedeawy 
Unfortunately:

Do i have to link a special resolver or something?

[error] (*:update) sbt.ResolveException: download failed: com.typesafe.play#sbt-fork-run-protocol_2.10;2.4.0!sbt-fork-run-protocol_2.10.jar
(*:31mupdate0m) sbt.ResolveException: download failed: com.typesafe.play#sbt-fork-run-protocol_2.10;2.4.0!sbt-fork-run-protocol_2.10.jar
> load-failed
Failed to load project.

**Comment by Gbedeawy** [comment]
which version of scala are you using in build.sbt
```scalaVersion := "2.11.6"``` ??

**Comment by Hajtosek** [comment]
@Gbedeawy 
Yes I'm using scalaVersion := "2.11.6", i have also tried using 2.11.1

**Comment by jamesward** [comment]
Same issue here.

**Comment by jamesward** [comment]
Duplicate of:
https://github.com/playframework/playframework/issues/4563

**Comment by Gbedeawy** [comment]
try running activator now it's updating to version 1.3.4
hope it works

**Comment by henrikengstrom** [comment]
The reason for this problem is that the Play versions in the ``project/plugins.sbt`` and the auto-generated file ``project/play-fork-run.sbt`` are not aligned. The latter contains an old version and this causes the error.
We are working on a fix to be shipped asap. Thanks for reporting.

**Comment by Gbedeawy** [comment]
changes 
```project/build.properties```
sbt version to this
```sbt.version=0.13.8```
and
```play-fork-run.sbt```
to
```addSbtPlugin("com.typesafe.play" % "sbt-fork-run-plugin" % "2.4.0")```

and tell me :smile:

**Comment by Hajtosek** [comment]
@Gbedeawy 
It works, for now.

**Comment by tonyfunc** [comment]
@Gbedeawy Thanks for the resolution! It works for me as well!

**Comment by cpoliwoda** [comment]
I tried the activator 1.3.5 with the hello-scala project but in the firefox browser the Typesafe Activator shows: "Failed to load sbt configurati..." and I can not run the project. The buid.properties in "hello-scala" are already set to sbt.version=0.13.8

**Comment by halfabench** [comment]
Same as @cpoliwoda  on windows 7.

**Comment by halfabench** [comment]
Sorry, my fault! So with the changes mentionned by @ElBedeawi it works with 1.3.5.

**Comment by halfabench** [comment]
Oh? In fact I can create the project (sounded good) but the sbt config still fails ('Failed to load sbt configuration').

error: java.lang.IllegalArgumentException: URI has an authority component

server log

 @6n5igeni5 - Internal server error, for (GET) [/api/app/connect/98ca04ce-02df-4605-b800-6385da9ae7bb?token=f69181becb4f76264a763aa6af182bdc77c0cbdd-1439459666178-58518eb7d26ae7af464c8b79] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: No app found with socket ID 98ca04ce-02df-4605-b800-6385da9ae7bb, we have these ids: Set()]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.9.jar:2.3.9]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$2.applyOrElse(PlayDefaultUpstreamHandler.scala:229) [play_2.11-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$2.applyOrElse(PlayDefaultUpstreamHandler.scala:227) [play_2.11-2.3.9.jar:2.3.9]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library.jar:0.13.8]
Caused by: java.lang.RuntimeException: No app found with socket ID 98ca04ce-02df-4605-b800-6385da9ae7bb, we have these ids: Set()
        at activator.AppCacheActor$$anonfun$receive$1.applyOrElse(AppManager.scala:115) ~[activator-ui-1.3.5.jar:1.3.5]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.9.jar:na]
        at activator.AppCacheActor.aroundReceive(AppManager.scala:38) ~[activator-ui-1.3.5.jar:1.3.5]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.9.jar:na]
[error] application -

! @6n5igf29h - Internal server error, for (GET) [/api/app/connect/98ca04ce-02df-4605-b800-6385da9ae7bb?token=f69181becb4f76264a763aa6af182bdc77c0cbdd-1439459666178-58518eb7d26ae7af464c8b79] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: No app found with socket ID 98ca04ce-02df-4605-b800-6385da9ae7bb, we have these ids: Set()]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.9.jar:2.3.9]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$2.applyOrElse(PlayDefaultUpstreamHandler.scala:229) [play_2.11-2.3.9.jar:2.3.9]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$2.applyOrElse(PlayDefaultUpstreamHandler.scala:227) [play_2.11-2.3.9.jar:2.3.9]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library.jar:0.13.8]
Caused by: java.lang.RuntimeException: No app found with socket ID 98ca04ce-02df-4605-b800-6385da9ae7bb, we have these ids: Set()
        at activator.AppCacheActor$$anonfun$receive$1.applyOrElse(AppManager.scala:115) ~[activator-ui-1.3.5.jar:1.3.5]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.9.jar:na]
        at activator.AppCacheActor.aroundReceive(AppManager.scala:38) ~[activator-ui-1.3.5.jar:1.3.5]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.9.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.9.jar:na]

Sorry for the mess.

**Comment by halfabench** [comment]
Kind of "solved" with solution mentionned by @mprentic-harris (https://github.com/typesafehub/activator/issues/1033):
>Deleting ~/.sbt/ did not work for me on Windows 7 with Play 2.4.2 and activator 1.3.2. I also did not have a ~/.sbt/repositories file. But after deleting ~/.sbt/ and running activator, I received the same exception,but it created the ~/.sbt/repositories file. Changing the local URLs from file:// to file:/// resolved the error and let me finally run my projects with activator and SBT 0.13.8.
