### ISSUE TITLE
INFO: Unable to execute HTTP request: peer not authenticated javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

### ISSUE THREAD

**Issue by imyque** [typesafehub/activator#1047]
Hello People,

I tried to create a new project and I got the error listed below.

Thank you for your help.
M.I. 

**Environment:**
Mac OS X 10.10.2
Activator 1.3.5
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
javac 1.8.0_25

**Error:**
```
XXXane:~ xxxane$ activator new

Fetching the latest list of templates...

Jun 22, 2015 11:50:16 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: peer not authenticated
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:390)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:104)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository.scala:135)
	at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepository.scala:238)
	at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:192)
	at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:190)
	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepository.scala:190)
	at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.scala:184)
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Jun 22, 2015 11:50:17 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: peer not authenticated
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:390)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:104)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository.scala:135)
	at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepository.scala:238)
	at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:192)
	at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:190)
	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepository.scala:190)
	at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.scala:184)
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Jun 22, 2015 11:50:19 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: peer not authenticated
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:390)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:104)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository.scala:135)
	at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepository.scala:238)
	at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:192)
	at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:190)
	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepository.scala:190)
	at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.scala:184)
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Jun 22, 2015 11:50:22 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: peer not authenticated
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:390)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:104)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository.scala:135)
	at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepository.scala:238)
	at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:192)
	at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:190)
	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
	at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepository.scala:190)
	at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.scala:184)
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[WARN] [06/22/2015 11:50:22.087] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Failed to grab s3 bucket, attempting to use http to 'http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties'. (Failed to download http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties from s3: com.amazonaws.AmazonClientException: Unable to execute HTTP request: peer not authenticated)
[ERROR] [06/22/2015 11:50:25.819] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Failed to download http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties: sbt.TranslatedIOException: Error opening http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties: java.net.SocketException: Connection reset
[WARN] [06/22/2015 11:50:25.822] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Failed to download new template catalog properties: activator.templates.repository.RepositoryException: Failed to download http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties: sbt.TranslatedIOException: Error opening http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties: java.net.SocketException: Connection reset
Browse the list of templates: http://typesafe.com/activator/templates
Choose from these featured templates or enter a template name:
  1) minimal-akka-java-seed
  2) minimal-akka-scala-seed
  3) minimal-java
  4) minimal-scala
  5) play-java
  6) play-scala
(hit tab to see a list of all templates)
> XXXane:~ xxxane$ 
```

**Comment by corruptmemory** [comment]
It appears that this is a long-standing problem with no good resolution:
https://forums.aws.amazon.com/message.jspa?messageID=429971

The suggested answer from Amazon doesn't seem like a good idea (effectively disabling SSL checks).

Couple things to look at:
* It appears that Oracle's JDK is less affected by this problem (possibly update your version of Java?)
* Some of the posters indicate that a timing problem may be involved: make sure your NTP-based time is set up correctly.

**Comment by eed3si9n** [comment]
I'm using OS X Yosemite, 10.10.3, and I was not able to reproduce this.

```sh
[X:~]$ cd Downloads/activator-1.3.5-minimal 
[X:~/Downloads/activator-1.3.5-minimal]$ ls
activator*                  activator.bat*
activator-launch-1.3.5.jar
[X:~/Downloads/activator-1.3.5-minimal]$ jdk8 zsh 
[X:~/Downloads/activator-1.3.5-minimal]$ java -version
java version "1.8.0_40-ea"
Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b23)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
[X:~/Downloads/activator-1.3.5-minimal]$ ./activator new

Fetching the latest list of templates...

Browse the list of templates: http://typesafe.com/activator/templates
Choose from these featured templates or enter a template name:
  1) minimal-akka-java-seed
  2) minimal-akka-scala-seed
  3) minimal-java
  4) minimal-scala
  5) play-java
  6) play-scala
(hit tab to see a list of all templates)
> 
```

**Comment by imyque** [comment]
Hi Eed3si9n,

I upgraded to OS X 10.10.3 and java to 1.8.0_45 and everything is fine now. 

Thanks.

**Comment by eed3si9n** [comment]
Awesome.
