### ISSUE TITLE
Failed to create new project using activator, and here some error messages!

### ISSUE THREAD

**Issue by netroby** [typesafehub/activator#1053]
```
activator new

Fetching the latest list of templates...

Jun 27, 2015 8:08:12 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:104)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository.scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepository.scala:238)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:192)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:190)
        at sbt.IO$.withTemporaryDirectory(IO.scala:291)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepository.scala:190)
        at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.scala:184)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Jun 27, 2015 8:08:18 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:104)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository.scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepository.scala:238)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:192)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:190)
        at sbt.IO$.withTemporaryDirectory(IO.scala:291)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepository.scala:190)
        at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.scala:184)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Jun 27, 2015 8:08:24 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:104)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository.scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepository.scala:238)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:192)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:190)
        at sbt.IO$.withTemporaryDirectory(IO.scala:291)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepository.scala:190)
        at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.scala:184)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Jun 27, 2015 8:08:31 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:104)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository.scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepository.scala:238)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:192)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRemoteTemplateRepository.scala:190)
        at sbt.IO$.withTemporaryDirectory(IO.scala:291)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepository.scala:190)
        at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.scala:184)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[WARN] [06/27/2015 08:08:31.769] [default-akka.actor.default-dispatcher-4] [ActorSystem(default)] Failed to grab s3 bucket, attempting to use http to 'http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties'. (Failed to download http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties from s3: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.16.248 timed out)

Could not fetch the updated list of templates.  Using the local cache.
Check your proxy settings or increase the timeout.  For more details see:
http://typesafe.com/activator/docs

[ERROR] [06/27/2015 08:08:32.070] [fallback-akka.actor.default-dispatcher-4] [akka://fallback/user/template-cache] Could not find a template catalog. (activator.templates.repository.RepositoryException: We don't have /home/huzhifeng/.activator/1.3.5/templates/cache.properties with an index hash in it, even though we should have downloaded one
activator.templates.repository.RepositoryException: We don't have /home/huzhifeng/.activator/1.3.5/templates/cache.properties with an index hash in it, even though we should have downloaded one
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:184)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
activator.templates.repository.RepositoryException: We don't have /home/huzhifeng/.activator/1.3.5/templates/cache.properties with an index hash in it, even though we should have downloaded one
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:184)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by corruptmemory** [comment]
A suggestion would be to follow the instructions in this comment: https://github.com/typesafehub/activator/issues/1054#issuecomment-118968809 and see if things improve.  It would appear that you are having connectivity problems to Amazon S3.
