### ISSUE TITLE
module not found error in new created activator project

### ISSUE THREAD

**Issue by lxyu** [typesafehub/activator#1059]
Scala version 2.11.7, Activator version 1.3.5.

Create a new `play-scala` with `activator new` and run `activator` in the directory give this error.

```
$ activator
[info] Loading project definition from /tmp/play-scala/project
[info] Updating {file:/tmp/play-scala/project/}play-scala-build...
[info] Resolving com.typesafe.play#sbt-plugin;2.4.2 ...
[warn] 	module not found: com.typesafe.play#sbt-plugin;2.4.2
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.4.2/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.4.2/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/lxyu/.ivy2/local/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.4.2/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /usr/share/typesafe-activator/repository/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.4.2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/sbt-plugin_2.10_0.13/2.4.2/sbt-plugin-2.4.2.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/play/sbt-plugin_2.10_0.13/2.4.2/sbt-plugin-2.4.2.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/sbt-plugin/scala_2.10/sbt_0.13/2.4.2/ivys/ivy.xml
[info] Resolving com.typesafe.sbt#sbt-coffeescript;1.0.0 ...
[warn] 	module not found: com.typesafe.sbt#sbt-coffeescript;1.0.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-coffeescript/scala_2.10/sbt_0.13/1.0.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-coffeescript/scala_2.10/sbt_0.13/1.0.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/lxyu/.ivy2/local/com.typesafe.sbt/sbt-coffeescript/scala_2.10/sbt_0.13/1.0.0/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /usr/share/typesafe-activator/repository/com.typesafe.sbt/sbt-coffeescript/scala_2.10/sbt_0.13/1.0.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-coffeescript_2.10_0.13/1.0.0/sbt-coffeescript-1.0.0.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-coffeescript_2.10_0.13/1.0.0/sbt-coffeescript-1.0.0.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-coffeescript/scala_2.10/sbt_0.13/1.0.0/ivys/ivy.xml
[info] Resolving com.typesafe.sbt#sbt-less;1.0.6 ...
[warn] 	module not found: com.typesafe.sbt#sbt-less;1.0.6
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-less/scala_2.10/sbt_0.13/1.0.6/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-less/scala_2.10/sbt_0.13/1.0.6/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/lxyu/.ivy2/local/com.typesafe.sbt/sbt-less/scala_2.10/sbt_0.13/1.0.6/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /usr/share/typesafe-activator/repository/com.typesafe.sbt/sbt-less/scala_2.10/sbt_0.13/1.0.6/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-less_2.10_0.13/1.0.6/sbt-less-1.0.6.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-less_2.10_0.13/1.0.6/sbt-less-1.0.6.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-less/scala_2.10/sbt_0.13/1.0.6/ivys/ivy.xml
[info] Resolving com.typesafe.sbt#sbt-jshint;1.0.3 ...
[A
[info] Resolving com.typesafe.sbt#sbt-jshint;1.0.3 ...
[warn] 	module not found: com.typesafe.sbt#sbt-jshint;1.0.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-jshint/scala_2.10/sbt_0.13/1.0.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-jshint/scala_2.10/sbt_0.13/1.0.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/lxyu/.ivy2/local/com.typesafe.sbt/sbt-jshint/scala_2.10/sbt_0.13/1.0.3/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /usr/share/typesafe-activator/repository/com.typesafe.sbt/sbt-jshint/scala_2.10/sbt_0.13/1.0.3/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-jshint_2.10_0.13/1.0.3/sbt-jshint-1.0.3.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-jshint_2.10_0.13/1.0.3/sbt-jshint-1.0.3.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-jshint/scala_2.10/sbt_0.13/1.0.3/ivys/ivy.xml
[info] Resolving com.typesafe.sbt#sbt-rjs;1.0.7 ...
[A
[info] Resolving com.typesafe.sbt#sbt-rjs;1.0.7 ...
[warn] 	module not found: com.typesafe.sbt#sbt-rjs;1.0.7
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-rjs/scala_2.10/sbt_0.13/1.0.7/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-rjs/scala_2.10/sbt_0.13/1.0.7/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/lxyu/.ivy2/local/com.typesafe.sbt/sbt-rjs/scala_2.10/sbt_0.13/1.0.7/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /usr/share/typesafe-activator/repository/com.typesafe.sbt/sbt-rjs/scala_2.10/sbt_0.13/1.0.7/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-rjs_2.10_0.13/1.0.7/sbt-rjs-1.0.7.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-rjs_2.10_0.13/1.0.7/sbt-rjs-1.0.7.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-rjs/scala_2.10/sbt_0.13/1.0.7/ivys/ivy.xml
[info] Resolving com.typesafe.sbt#sbt-digest;1.1.0 ...
[A
[info] Resolving com.typesafe.sbt#sbt-digest;1.1.0 ...
[warn] 	module not found: com.typesafe.sbt#sbt-digest;1.1.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-digest/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-digest/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/lxyu/.ivy2/local/com.typesafe.sbt/sbt-digest/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /usr/share/typesafe-activator/repository/com.typesafe.sbt/sbt-digest/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-digest_2.10_0.13/1.1.0/sbt-digest-1.1.0.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-digest_2.10_0.13/1.1.0/sbt-digest-1.1.0.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-digest/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[info] Resolving com.typesafe.sbt#sbt-mocha;1.1.0 ...
[A
[info] Resolving com.typesafe.sbt#sbt-mocha;1.1.0 ...
[warn] 	module not found: com.typesafe.sbt#sbt-mocha;1.1.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-mocha/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-mocha/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /home/lxyu/.ivy2/local/com.typesafe.sbt/sbt-mocha/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   /usr/share/typesafe-activator/repository/com.typesafe.sbt/sbt-mocha/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-mocha_2.10_0.13/1.1.0/sbt-mocha-1.1.0.pom
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/sbt/sbt-mocha_2.10_0.13/1.1.0/sbt-mocha-1.1.0.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-mocha/scala_2.10/sbt_0.13/1.1.0/ivys/ivy.xml
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[A
[info] Resolving org.scala-sbt#sbt;0.13.8 ...
[A
[info] Resolving org.scala-sbt#main;0.13.8 ...
[A
[info] Resolving org.scala-sbt#actions;0.13.8 ...
[A
[info] Resolving org.scala-sbt#classpath;0.13.8 ...
[A
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
[A
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[A
[info] Resolving org.scala-sbt#launcher-interface;0.13.8 ...
[A
[info] Resolving org.scala-sbt#interface;0.13.8 ...
[A
[info] Resolving org.scala-sbt#io;0.13.8 ...
[A
[info] Resolving org.scala-sbt#control;0.13.8 ...
[A
[info] Resolving org.scala-sbt#completion;0.13.8 ...
[A
[info] Resolving org.scala-sbt#collections;0.13.8 ...
[A
[info] Resolving jline#jline;2.11 ...
[A
[info] Resolving org.scala-sbt#api;0.13.8 ...
[A
[info] Resolving org.scala-sbt#compiler-integration;0.13.8 ...
[A
[info] Resolving org.scala-sbt#incremental-compiler;0.13.8 ...
[A
[info] Resolving org.scala-sbt#logging;0.13.8 ...
[A
[info] Resolving org.scala-sbt#process;0.13.8 ...
[A
[info] Resolving org.scala-sbt#relation;0.13.8 ...
[A
[info] Resolving org.scala-sbt#compile;0.13.8 ...
[A
[info] Resolving org.scala-sbt#classfile;0.13.8 ...
[A
[info] Resolving org.scala-sbt#persist;0.13.8 ...
[A
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[A
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.8 ...
[A
[info] Resolving org.scala-sbt#ivy;0.13.8 ...
[A
[info] Resolving org.scala-sbt#cross;0.13.8 ...
[A
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f ...
[A
[info] Resolving com.jcraft#jsch;0.1.46 ...
[A
[info] Resolving org.scala-sbt#serialization_2.10;0.1.1 ...
[A
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.0 ...
[A
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[A
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[A
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[A
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[A
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[A
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[A
[info] Resolving org.scala-sbt#run;0.13.8 ...
[A
[info] Resolving org.scala-sbt#task-system;0.13.8 ...
[A
[info] Resolving org.scala-sbt#tasks;0.13.8 ...
[A
[info] Resolving org.scala-sbt#tracking;0.13.8 ...
[A
[info] Resolving org.scala-sbt#cache;0.13.8 ...
[A
[info] Resolving org.scala-sbt#testing;0.13.8 ...
[A
[info] Resolving org.scala-sbt#test-agent;0.13.8 ...
[A
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[A
[info] Resolving org.scala-sbt#main-settings;0.13.8 ...
[A
[info] Resolving org.scala-sbt#apply-macro;0.13.8 ...
[A
[info] Resolving org.scala-sbt#command;0.13.8 ...
[A
[info] Resolving org.scala-sbt#logic;0.13.8 ...
[A
[info] Resolving org.scala-sbt#compiler-interface;0.13.8 ...
[A
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.8 ...
[A
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.8 ...
[A
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.8 ...
[A
[info] Resolving org.scala-lang#jline;2.10.4 ...
[A
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#sbt-plugin;2.4.2: not found
[warn] 	:: com.typesafe.sbt#sbt-coffeescript;1.0.0: not found
[warn] 	:: com.typesafe.sbt#sbt-less;1.0.6: not found
[warn] 	:: com.typesafe.sbt#sbt-jshint;1.0.3: not found
[warn] 	:: com.typesafe.sbt#sbt-rjs;1.0.7: not found
[warn] 	:: com.typesafe.sbt#sbt-digest;1.1.0: not found
[warn] 	:: com.typesafe.sbt#sbt-mocha;1.1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbt:sbt-less:1.0.6 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-jshint:1.0.3 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-coffeescript:1.0.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-mocha:1.1.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.play:sbt-plugin:2.4.2 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-digest:1.1.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-rjs:1.0.7 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.sbt:sbt-less:1.0.6 (scalaVersion=2.10, sbtVersion=0.13) (/tmp/play-scala/project/plugins.sbt#L8-9)
[warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-jshint:1.0.3 (scalaVersion=2.10, sbtVersion=0.13) (/tmp/play-scala/project/plugins.sbt#L10-11)
[warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-coffeescript:1.0.0 (scalaVersion=2.10, sbtVersion=0.13) (/tmp/play-scala/project/plugins.sbt#L6-7)
[warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-mocha:1.1.0 (scalaVersion=2.10, sbtVersion=0.13) (/tmp/play-scala/project/plugins.sbt#L16-17)
[warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.play:sbt-plugin:2.4.2 (scalaVersion=2.10, sbtVersion=0.13) (/tmp/play-scala/project/plugins.sbt#L2-3)
[warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-digest:1.1.0 (scalaVersion=2.10, sbtVersion=0.13) (/tmp/play-scala/project/plugins.sbt#L14-15)
[warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		com.typesafe.sbt:sbt-rjs:1.0.7 (scalaVersion=2.10, sbtVersion=0.13) (/tmp/play-scala/project/plugins.sbt#L12-13)
[warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-plugin;2.4.2: not found
unresolved dependency: com.typesafe.sbt#sbt-coffeescript;1.0.0: not found
unresolved dependency: com.typesafe.sbt#sbt-less;1.0.6: not found
unresolved dependency: com.typesafe.sbt#sbt-jshint;1.0.3: not found
unresolved dependency: com.typesafe.sbt#sbt-rjs;1.0.7: not found
unresolved dependency: com.typesafe.sbt#sbt-digest;1.1.0: not found
unresolved dependency: com.typesafe.sbt#sbt-mocha;1.1.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-plugin;2.4.2: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-coffeescript;1.0.0: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-less;1.0.6: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-jshint;1.0.3: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-rjs;1.0.7: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-digest;1.1.0: not found
[error] unresolved dependency: com.typesafe.sbt#sbt-mocha;1.1.0: not found
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by lxyu** [comment]
I'll close this as it works today... seems to be a tmp network failure.
