### ISSUE TITLE
Activator does not work as shown in the see-it-in-action video

### ISSUE THREAD

**Issue by veita** [typesafehub/activator#1066]
After working around issues https://github.com/typesafehub/activator/issues/1033 and https://github.com/typesafehub/activator/issues/1058 activator 1.3.5 fails to create the Reactives Stocks project.

For me the software is not usable for over 2 months now. This is surprising since the Activator seems to be the declared starting point to dive into the Typesafe Reactive Platform (see http://www.typesafe.com/get-started).

```
[warn]
[warn] Note: Unresolved dependencies path:
Note: Unresolved dependencies path:
[warn] org.javassist:javassist:3.19.0-GA
org.javassist:javassist:3.19.0-GA
[warn] +- com.typesafe.play:build-link:2.4.0
+- com.typesafe.play:build-link:2.4.0
[warn] +- com.typesafe.play:sbt-run-support_2.10:2.4.0
+- com.typesafe.play:sbt-run-support_2.10:2.4.0
[warn] +- com.typesafe.play:sbt-plugin:2.4.0 (scalaVersion=2.10, sbtVersion=0.13) (D:\prj\scala\reactive-stocks\project\plugins.sbt#L8-9)
+- com.typesafe.play:sbt-plugin:2.4.0 (scalaVersion=2.10, sbtVersion=0.13) (D:\prj\scala\reactive-stocks\project\plugins.sbt#L8-9)
[warn] +- default:reactive-stocks-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
+- default:reactive-stocks-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
unresolved dependency: org.javassist#javassist;3.19.0-GA: configuration not found in org.javassist#javassist;3.19.0-GA: 'master(compile)'. Missing configuration: 'compile'. It was required from com.typesafe.play#build-link;2.4.0 compile
sbt.ResolveException: unresolved dependency: org.javassist#javassist;3.19.0-GA: configuration not found in org.javassist#javassist;3.19.0-GA: 'master(compile)'. Missing configuration: 'compile'. It was required from com.typesafe.play#build-link;2.4.0 compile
at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
at xsbt.boot.Using$.withResource(Using.scala:10)
at xsbt.boot.Using$.apply(Using.scala:9)
at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
at xsbt.boot.Locks$.apply0(Locks.scala:31)
at xsbt.boot.Locks$.apply(Locks.scala:28)
at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
at sbt.IvySbt.withIvy(Ivy.scala:127)
at sbt.IvySbt.withIvy(Ivy.scala:124)
at sbt.IvySbt$Module.withModule(Ivy.scala:155)
at sbt.IvyActions$.updateEither(IvyActions.scala:165)
at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
at sbt.std.Transform$$anon$4.work(System.scala:63)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
at sbt.Execute.work(Execute.scala:235)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.javassist#javassist;3.19.0-GA: configuration not found in org.javassist#javassist;3.19.0-GA: 'master(compile)'. Missing configuration: 'compile'. It was required from com.typesafe.play#build-link;2.4.0 compile
(*:update) sbt.ResolveException: unresolved dependency: org.javassist#javassist;3.19.0-GA: configuration not found in org.javassist#javassist;3.19.0-GA: 'master(compile)'. Missing configuration: 'compile'. It was required from com.typesafe.play#build-link;2.4.0 compile
Failed to load project.
```

Activator 1.3.5
Java 1.8.0_45
Windows 7

**Comment by ishepherd** [comment]
+1
