### ISSUE TITLE
Dependency Ranges Not Working in Activator, but do work in SBT

### ISSUE THREAD

**Issue by nblomquist** [typesafehub/activator#1093]
Hello,
We have discovered a difference in how Activator does dependencies and how SBT does them.

An internal support library we created depends on:
`"com.google.code.findbugs" % "jsr305" % "1.3.+"`

When we include this support library and build with Activator, it will fail to resolve that transitive dependency.  Doing the same thing with SBT works fine.

I think this has to do with a bug that was just fixed in SBT 0.13.9:
https://github.com/sbt/sbt/issues/752

A quick way to reproduce this is to:
```
> activator new

Fetching the latest list of templates...

Browse the list of templates: http://typesafe.com/activator/templates
Choose from these featured templates or enter a template name:
  1) minimal-akka-java-seed
  2) minimal-akka-scala-seed
  3) minimal-java
  4) minimal-scala
  5) play-java
  6) play-scala
(hit tab to see a list of all templates)
> 5
Enter a name for your application (just press enter for 'play-java')
> test
OK, application "test" is being created using the "play-java" template.

To run "test" from the command line, "cd test" then:
C:\tmp\test\test\test/activator run

To run the test for "test" from the command line, "cd test" then:
C:\tmp\test\test\test/activator test

To run the Activator UI for "test" from the command line, "cd test" then:
C:\tmp\test\test\test/activator ui
```

Then change `project\build.properties` to have sbt 0.13.9.
Then change `build.sbt` to:
```
name := """test"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayJava)

scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  "com.google.code.findbugs" % "jsr305" % "1.3.+"
)

// Play provides two styles of routers, one expects its actions to be injected, the
// other, legacy style, accesses its actions statically.
routesGenerator := InjectedRoutesGenerator

```
This fails:
`activator clean compile`
This works:
`sbt clean compile`

Even with the build.properties change, Activator will still fail.

A co-worker discovered that his SBT would still fail to build because his sbt-launch.jar was 0.13.7.  Even though build.properties was set to 0.13.9 it would still fail.
Upgrading his SBT to sbt-launch.jar 0.13.9 resolved the issue.

What version of SBT is Activator built on?

Thanks.

Error message from Activator:
```
> activator clean compile
[info] Loading global plugins from C:\Users\<my-username>\.sbt\0.13\plugins
[info] Loading project definition from C:\tmp\test\test\project
[info] Set current project to test (in build file:/C:/tmp/test/test/)
[success] Total time: 0 s, completed Feb 1, 2016 12:25:03 PM
[info] Updating {file:/C:/tmp/test/test/}root...
[info] Resolving com.google.code.findbugs#jsr305;1.3.+ ...
[warn]  module not found: com.google.code.findbugs#jsr305;1.3.+
[warn] ==== local: tried
[warn]   C:\Users\<my-username>\.ivy2\local\com.google.code.findbugs\jsr305\[revision]\ivys\ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   C:\tmp\test\test\repository\com.google.code.findbugs\jsr305\[revision]\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/[revision]/jsr305-[revision].pom
[warn]   [3.0.1, 3.0.0, 2.0.3, 2.0.2]
[warn] ==== typesafe-releases: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/google/code/findbugs/jsr305/[revision]/jsr305-[revision].pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.google.code.findbugs/jsr305/[revision]/ivys/ivy.xml
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.google.code.findbugs#jsr305;1.3.+: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.google.code.findbugs:jsr305:1.3.+ (C:\tmp\test\test\build.sbt#L9-12)
[warn]            +- test:test_2.11:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.google.code.findbugs#jsr305;1.3.+: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.google.code.findbugs#jsr305;1.3.+: not found
[error] Total time: 14 s, completed Feb 1, 2016 12:25:17 PM
```

SBT Works fine:
```
> sbt clean compile
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading global plugins from C:\Users\<my-username>\.sbt\0.13\plugins
[info] Updating {file:/C:/Users/<my-username>/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from C:\tmp\test\test\project
[info] Updating {file:/C:/tmp/test/test/project/}test-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to test (in build file:/C:/tmp/test/test/)
[success] Total time: 0 s, completed Feb 1, 2016 12:28:16 PM
[info] Updating {file:/C:/tmp/test/test/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.google.code.findbugs:jsr305:1.3.9 -> 2.0.3
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 6 Scala sources and 2 Java sources to C:\tmp\test\test\target\scala-2.11\classes...
[success] Total time: 19 s, completed Feb 1, 2016 12:28:35 PM
```

**Comment by nblomquist** [comment]
Currently our workaround is:
* Create the Project with Activator
* Build with SBT

Is there any problems with that?  Like does Activator do more than the standard SBT during compile/packaging?
