### ISSUE TITLE
Hash-mismatch when downloading template catalog properties on initial run of activator

### ISSUE THREAD

**Issue by mattfeury** [typesafehub/activator#1096]
Hello, I was looking at investigating play/activator. I download the activator zip, put the files in my PATH, and attempt to run `activator new test play-scala`. In response I get

```
Fetching the latest list of templates...

[WARN] [02/23/2016 18:34:41.421] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Failed to download new template catalog properties: activator.templates.repository.RepositoryException: Expected hash of http://downloads.typesafe.com/typesafe-activator/index/v2/index-f6fd59c93add074a0844955bc2829f07e5029276.zip to be f6fd59c93add074a0844955bc2829f07e5029276 but it was cf909e7937cd3f312c434367b732a53d7a6cbf14
[ERROR] [02/23/2016 18:34:41.424] [default-akka.actor.default-dispatcher-3] [akka://default/user/template-cache] Could not find a template catalog. (activator.templates.repository.RepositoryException: We don't have /Users/Lombardi/.activator/1.3.7/templates/cache.properties with an index hash in it, even though we should have downloaded one
activator.templates.repository.RepositoryException: We don't have /Users/Lombardi/.activator/1.3.7/templates/cache.properties with an index hash in it, even though we should have downloaded one
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:184)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

activator.templates.repository.RepositoryException: We don't have /Users/Lombardi/.activator/1.3.7/templates/cache.properties with an index hash in it, even though we should have downloaded one
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:184)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Looks like a hash mismatch: `[WARN] [02/23/2016 18:34:41.421] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Failed to download new template catalog properties: activator.templates.repository.RepositoryException: Expected hash of http://downloads.typesafe.com/typesafe-activator/index/v2/index-f6fd59c93add074a0844955bc2829f07e5029276.zip to be f6fd59c93add074a0844955bc2829f07e5029276 but it was cf909e7937cd3f312c434367b732a53d7a6cbf14`

Am I messing something up or did I [pick the wrong week](https://www.youtube.com/watch?v=hd1ciPnTGKg) to start writing play?

**Comment by yasargil** [comment]
Same Problem here:
play.api.Application$$anon$1: Execution exception[[RepositoryException: We don't have /Users/yasargil/.activator/1.3.7/templates/cache.properties with an index hash in it, even though we should have downloaded one]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.9.jar:2.3.9]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library.jar:0.13.8]
Caused by: activator.templates.repository.RepositoryException: We don't have /Users/yasargil/.activator/1.3.7/templates/cache.properties with an index hash in it, even though we should have downloaded one
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:184) ~[activator-templates-cache-1.0-a0afb008ea619bf9d87dc010156cddffa8a6f880.jar:1.0-a0afb008ea619bf9d87dc010156cddffa8a6f880]
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470) ~[akka-actor_2.11-2.3.9.jar:na]
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25) ~[activator-templates-cache-1.0-a0afb008ea619bf9d87dc010156cddffa8a6f880.jar:1.0-a0afb008ea619bf9d87dc010156cddffa8a6f880]
	at akka.actor.ActorCell.create(ActorCell.scala:580) ~[akka-actor_2.11-2.3.9.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[akka-actor_2.11-2.3.9.jar:na]

**Comment by reindeer77** [comment]
Same problem, activator 1.3.7,  java 1.8.0_73,  fresh installation.
Also tried removing .activator and .sbt
play.api.Application$$anon$1: Execution exception[[RepositoryException: We don't have C:\Users\Utente_2\.activator\1.3.7\templates\cache.properties with an index hash in it, even though we should have downloaded one]]

**Comment by fadeddata** [comment]
Same problem here. Is it because of the redirect to Lightbenders or whatever the new name is?

**Comment by mattfeury** [comment]
this is working for me now. must've been a hiccup in versioning
