### ISSUE TITLE
Unable to load sbt

### ISSUE THREAD

**Issue by JJ-Atkinson** [typesafehub/activator#1109]
I'm trying to use activator, but every time I open a project it says that it can't load the sbt config. This is the tail end of the build log:

    [info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.8 ...
    Resolving org.scala-sbt#precompiled-2_9_2;0.13.8 ...
    [info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.8 ...
    Resolving org.scala-sbt#precompiled-2_9_3;0.13.8 ...
    [info] Resolving org.scala-lang#jline;2.10.4 ...
    Resolving org.scala-lang#jline;2.10.4 ...
    [info] Resolving org.fusesource.jansi#jansi;1.4 ...
    Resolving org.fusesource.jansi#jansi;1.4 ...
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	::          UNRESOLVED DEPENDENCIES         ::
    	::          UNRESOLVED DEPENDENCIES         ::
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	:: commons-io#commons-io;2.4: configuration not found in commons-io#commons-io;2.4: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    	:: commons-io#commons-io;2.4: configuration not found in commons-io#commons-io;2.4: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    [warn] 	:: org.apache.ant#ant;1.9.3: configuration not found in org.apache.ant#ant;1.9.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    	:: org.apache.ant#ant;1.9.3: configuration not found in org.apache.ant#ant;1.9.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 
    [warn] 	Note: Unresolved dependencies path:
    
    	Note: Unresolved dependencies path:
    [warn] 		commons-io:commons-io:2.4
    		commons-io:commons-io:2.4
    [warn] 		  +- org.vafer:jdeb:1.3
    		  +- org.vafer:jdeb:1.3
    [warn] 		  +- com.typesafe.sbt:sbt-native-packager:1.0.3 (scalaVersion=2.10, sbtVersion=0.13)
    		  +- com.typesafe.sbt:sbt-native-packager:1.0.3 (scalaVersion=2.10, sbtVersion=0.13)
    [warn] 		  +- com.typesafe.play:sbt-plugin:2.5.1 (scalaVersion=2.10, sbtVersion=0.13) (C:\code-projects\play-scala\project\plugins.sbt#L2-3)
    		  +- com.typesafe.play:sbt-plugin:2.5.1 (scalaVersion=2.10, sbtVersion=0.13) (C:\code-projects\play-scala\project\plugins.sbt#L2-3)
    [warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
    		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
    [warn] 		org.apache.ant:ant:1.9.3
    		org.apache.ant:ant:1.9.3
    [warn] 		  +- org.vafer:jdeb:1.3
    		  +- org.vafer:jdeb:1.3
    [warn] 		  +- com.typesafe.sbt:sbt-native-packager:1.0.3 (scalaVersion=2.10, sbtVersion=0.13)
    		  +- com.typesafe.sbt:sbt-native-packager:1.0.3 (scalaVersion=2.10, sbtVersion=0.13)
    [warn] 		  +- com.typesafe.play:sbt-plugin:2.5.1 (scalaVersion=2.10, sbtVersion=0.13) (C:\code-projects\play-scala\project\plugins.sbt#L2-3)
    		  +- com.typesafe.play:sbt-plugin:2.5.1 (scalaVersion=2.10, sbtVersion=0.13) (C:\code-projects\play-scala\project\plugins.sbt#L2-3)
    [warn] 		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
    		  +- default:play-scala-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
    unresolved dependency: commons-io#commons-io;2.4: configuration not found in commons-io#commons-io;2.4: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    unresolved dependency: org.apache.ant#ant;1.9.3: configuration not found in org.apache.ant#ant;1.9.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    sbt.ResolveException: unresolved dependency: commons-io#commons-io;2.4: configuration not found in commons-io#commons-io;2.4: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    unresolved dependency: org.apache.ant#ant;1.9.3: configuration not found in org.apache.ant#ant;1.9.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
    	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
    	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
    	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
    	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
    	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
    	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
    	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    	at xsbt.boot.Using$.withResource(Using.scala:10)
    	at xsbt.boot.Using$.apply(Using.scala:9)
    	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    	at xsbt.boot.Locks$.apply0(Locks.scala:31)
    	at xsbt.boot.Locks$.apply(Locks.scala:28)
    	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
    	at sbt.IvySbt.withIvy(Ivy.scala:127)
    	at sbt.IvySbt.withIvy(Ivy.scala:124)
    	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
    	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
    	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
    	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
    	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
    	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
    	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
    	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
    	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
    	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
    	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
    	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
    	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
    	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    	at sbt.std.Transform$$anon$4.work(System.scala:63)
    	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    	at sbt.Execute.work(Execute.scala:235)
    	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    [error] (*:update) sbt.ResolveException: unresolved dependency: commons-io#commons-io;2.4: configuration not found in commons-io#commons-io;2.4: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    [error] unresolved dependency: org.apache.ant#ant;1.9.3: configuration not found in org.apache.ant#ant;1.9.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    (*:update) sbt.ResolveException: unresolved dependency: commons-io#commons-io;2.4: configuration not found in commons-io#commons-io;2.4: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    unresolved dependency: org.apache.ant#ant;1.9.3: configuration not found in org.apache.ant#ant;1.9.3: 'master(compile)'. Missing configuration: 'compile'. It was required from org.vafer#jdeb;1.3 compile
    Failed to load project.

This is my repositories file:

    [repositories]
      local
      activator-launcher-local: file:////${activator.local.repository-${activator.home-${user.home}/.activator}/repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
      activator-local: file:////${activator.local.repository-C:/code-projects/activator/activator-dist-1.3.9//repository}, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
      maven-central
      typesafe-releases: http://repo.typesafe.com/typesafe/releases
      typesafe-ivy-releasez: http://repo.typesafe.com/typesafe/ivy-releases, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]

I'm unable to load any project that uses play. If I load a project that doesn't use play all's good...

### Things I've tried

 - Delete everything in my `.sbt` folder
 - Remove the `activator.*` lines from my repositories file, before and during running activator
 - Remove the `fork in run := true` line from my `build.sbt` file (It is put back in every time I restart)
 - Add `addSbtPlugin("com.typesafe.play" % "sbt-fork-run-plugin" % "2.4.0")` to my `plugins.sbt` file (the plugin wasn't there before I added it)

### Some related pages

 - https://github.com/typesafehub/activator/issues/1037
 - https://github.com/typesafehub/activator/issues/1033
 - https://github.com/typesafehub/activator/issues/1034
 - https://github.com/typesafehub/activator/issues/1036
 - http://stackoverflow.com/questions/31534892/sbt-configuration-failed-to-load-in-typesafe-activator
 - More that I can't remember right now

### Version info

 - Activator -> 1.3.9
 - Sbt -> 0.13.8
 - OS -> Windows 10

Does anyone know how to fix this?

**Comment by JJ-Atkinson** [comment]
I resolved the issue by removing the items that were causing issues from the ivy cache. http://grokbase.com/t/gg/play-framework/148nyqebp9/commion-io-configuration-not-found

**Comment by felixaballi** [comment]
I use in plugins.sbt, the play2 version is 2.5.1 "streamy". But I have the same problems.
I erased all data inside the forum's answer:
..\.ivy2\cache\commons-io
But without success.

If I change the sbt version would be of any help?
What older version works?

addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.1")
