### ISSUE TITLE
play-scala-intro example fails in IntelliJ

### ISSUE THREAD

**Issue by werezak** [typesafehub/activator#1111]
Using Activator 1.3.9, the play-scala-intro template will work but requires that there be a SQL script update done by the user in the web app itself.  After clicking the button, the app works.

But when the project is imported into IntelliJ 2016.1 (the latest as of 12APR2016) with the IntelliJ Scala Plugin v3.0.2, the above error occurs along with an addition Javascript problem. I've seen this problem referred to on StackOverflow for past iterations of this template with no clear resolution. 

The javascript error is:

c.g.h.h.HtmlPage - Error loading JavaScript from [http://localhost:19001/assets/javascripts/index.js].
java.io.IOException: Unable to download JavaScript from 'http://localhost:19001/assets/javascripts/index.js' (status 404).

Here is the trace:
`/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7534 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA.app/Contents/bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/tools.jar:/Users/user/IdeaProjects/play-scala-intro/target/scala-2.11/test-classes:/Users/user/IdeaProjects/play-scala-intro/target/scala-2.11/classes:/Users/user/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:/Users/user/.ivy2/cache/xml-apis/xml-apis/jars/xml-apis-1.4.01.jar:/Users/user/.ivy2/cache/xerces/xercesImpl/jars/xercesImpl-2.11.0.jar:/Users/user/.ivy2/cache/xalan/xalan/jars/xalan-2.7.2.jar:/Users/user/.ivy2/cache/xalan/serializer/jars/serializer-2.7.2.jar:/Users/user/.ivy2/cache/org.webbitserver/webbit/jars/webbit-0.4.14.jar:/Users/user/.ivy2/cache/org.w3c.css/sac/jars/sac-1.3.jar:/Users/user/.ivy2/cache/org.spire-math/kind-projector_2.11/jars/kind-projector_2.11-0.7.1.jar:/Users/user/.ivy2/cache/org.specs2/specs2-mock_2.11/jars/specs2-mock_2.11-3.6.6.jar:/Users/user/.ivy2/cache/org.specs2/specs2-matcher_2.11/jars/specs2-matcher_2.11-3.6.6.jar:/Users/user/.ivy2/cache/org.specs2/specs2-junit_2.11/jars/specs2-junit_2.11-3.6.6.jar:/Users/user/.ivy2/cache/org.specs2/specs2-core_2.11/jars/specs2-core_2.11-3.6.6.jar:/Users/user/.ivy2/cache/org.specs2/specs2-common_2.11/jars/specs2-common_2.11-3.6.6.jar:/Users/user/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.16.jar:/Users/user/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.16.jar:/Users/user/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.16.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-support/jars/selenium-support-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-safari-driver/jars/selenium-safari-driver-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-remote-driver/jars/selenium-remote-driver-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-leg-rc/jars/selenium-leg-rc-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-java/jars/selenium-java-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-ie-driver/jars/selenium-ie-driver-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-htmlunit-driver/jars/selenium-htmlunit-driver-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-firefox-driver/jars/selenium-firefox-driver-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-edge-driver/jars/selenium-edge-driver-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-chrome-driver/jars/selenium-chrome-driver-2.48.2.jar:/Users/user/.ivy2/cache/org.seleniumhq.selenium/selenium-api/jars/selenium-api-2.48.2.jar:/Users/user/.ivy2/cache/org.scodec/scodec-bits_2.11/bundles/scodec-bits_2.11-1.0.9.jar:/Users/user/.ivy2/cache/org.scalaz.stream/scalaz-stream_2.11/bundles/scalaz-stream_2.11-0.8.jar:/Users/user/.ivy2/cache/org.scalaz/scalaz-effect_2.11/bundles/scalaz-effect_2.11-7.1.4.jar:/Users/user/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.1.4.jar:/Users/user/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/bundles/scalaz-concurrent_2.11-7.1.4.jar:/Users/user/.ivy2/cache/org.scala-stm/scala-stm_2.11/jars/scala-stm_2.11-0.7.jar:/Users/user/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar:/Users/user/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.4.jar:/Users/user/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/Users/user/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar:/Users/user/.ivy2/cache/org.scala-lang.modules/scala-java8-compat_2.11/bundles/scala-java8-compat_2.11-0.7.0.jar:/Users/user/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.7.jar:/Users/user/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar:/Users/user/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.7.jar:/Users/user/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar:/Users/user/activator-dist-1.3.9/repository/org.objenesis/objenesis/1.0/jars/objenesis.jar:/Users/user/activator-dist-1.3.9/repository/org.mockito/mockito-core/1.9.5/jars/mockito-core.jar:/Users/user/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.8.1.jar:/Users/user/activator-dist-1.3.9/repository/org.javassist/javassist/3.19.0-GA/bundles/javassist.jar:/Users/user/.ivy2/cache/org.hamcrest/hamcrest-core/jars/hamcrest-core-1.3.jar:/Users/user/.ivy2/cache/org.fluentlenium/fluentlenium-core/jars/fluentlenium-core-0.10.9.jar:/Users/user/.ivy2/cache/org.eclipse.jetty.websocket/websocket-common/jars/websocket-common-9.2.15.v20160210.jar:/Users/user/.ivy2/cache/org.eclipse.jetty.websocket/websocket-client/jars/websocket-client-9.2.15.v20160210.jar:/Users/user/.ivy2/cache/org.eclipse.jetty.websocket/websocket-api/jars/websocket-api-9.2.15.v20160210.jar:/Users/user/.ivy2/cache/org.eclipse.jetty/jetty-util/jars/jetty-util-9.2.15.v20160210.jar:/Users/user/.ivy2/cache/org.eclipse.jetty/jetty-io/jars/jetty-io-9.2.15.v20160210.jar:/Users/user/.ivy2/cache/org.apache.httpcomponents/httpmime/jars/httpmime-4.5.2.jar:/Users/user/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.4.4.jar:/Users/user/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.5.2.jar:/Users/user/.ivy2/cache/org.apache.commons/commons-lang3/jars/commons-lang3-3.4.jar:/Users/user/.ivy2/cache/org.apache.commons/commons-exec/jars/commons-exec-1.3.jar:/Users/user/.ivy2/cache/net.sourceforge.nekohtml/nekohtml/jars/nekohtml-1.9.22.jar:/Users/user/.ivy2/cache/net.sourceforge.htmlunit/htmlunit-core-js/jars/htmlunit-core-js-2.17.jar:/Users/user/.ivy2/cache/net.sourceforge.htmlunit/htmlunit/jars/htmlunit-2.20.jar:/Users/user/.ivy2/cache/net.sourceforge.cssparser/cssparser/jars/cssparser-0.9.18.jar:/Users/user/.ivy2/cache/net.java.dev.jna/jna-platform/jars/jna-platform-4.1.0.jar:/Users/user/.ivy2/cache/net.java.dev.jna/jna/jars/jna-4.1.0.jar:/Users/user/.ivy2/cache/junit/junit/jars/junit-4.12.jar:/Users/user/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.2.jar:/Users/user/.ivy2/cache/javax.transaction/jta/jars/jta-1.1.jar:/Users/user/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar:/Users/user/.ivy2/cache/io.netty/netty-transport-native-epoll/jars/netty-transport-native-epoll-4.0.34.Final-linux-x86_64.jar:/Users/user/.ivy2/cache/io.netty/netty-transport/jars/netty-transport-4.0.34.Final.jar:/Users/user/.ivy2/cache/io.netty/netty-handler/jars/netty-handler-4.0.34.Final.jar:/Users/user/.ivy2/cache/io.netty/netty-common/jars/netty-common-4.0.34.Final.jar:/Users/user/.ivy2/cache/io.netty/netty-codec-http/jars/netty-codec-http-4.0.34.Final.jar:/Users/user/.ivy2/cache/io.netty/netty-codec/jars/netty-codec-4.0.34.Final.jar:/Users/user/.ivy2/cache/io.netty/netty-buffer/jars/netty-buffer-4.0.34.Final.jar:/Users/user/.ivy2/cache/io.netty/netty/bundles/netty-3.5.2.Final.jar:/Users/user/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.2.jar:/Users/user/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar:/Users/user/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.10.jar:/Users/user/.ivy2/cache/com.zaxxer/HikariCP-java6/bundles/HikariCP-java6-2.3.7.jar:/Users/user/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-3.1.0.jar:/Users/user/.ivy2/cache/com.typesafe.slick/slick-hikaricp_2.11/bundles/slick-hikaricp_2.11-3.1.0.jar:/Users/user/.ivy2/cache/com.typesafe.play/twirl-api_2.11/jars/twirl-api_2.11-1.1.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-test_2.11/jars/play-test_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-streams_2.11/jars/play-streams_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-specs2_2.11/jars/play-specs2_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-slick_2.11/jars/play-slick_2.11-1.1.0.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-slick-evolutions_2.11/jars/play-slick-evolutions_2.11-1.1.0.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-server_2.11/jars/play-server_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-netty-utils/jars/play-netty-utils-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-netty-server_2.11/jars/play-netty-server_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-logback_2.11/jars/play-logback_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-json_2.11/jars/play-json_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-jdbc-evolutions_2.11/jars/play-jdbc-evolutions_2.11-2.4.0.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-jdbc-api_2.11/jars/play-jdbc-api_2.11-2.4.0.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-iteratees_2.11/jars/play-iteratees_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-functional_2.11/jars/play-functional_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-exceptions/jars/play-exceptions-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/play-datacommons_2.11/jars/play-datacommons_2.11-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.play/build-link/jars/build-link-2.5.1.jar:/Users/user/.ivy2/cache/com.typesafe.netty/netty-reactive-streams-http/jars/netty-reactive-streams-http-1.0.5.jar:/Users/user/.ivy2/cache/com.typesafe.netty/netty-reactive-streams/jars/netty-reactive-streams-1.0.5.jar:/Users/user/.ivy2/cache/com.typesafe.akka/akka-stream_2.11/jars/akka-stream_2.11-2.4.2.jar:/Users/user/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.11/jars/akka-slf4j_2.11-2.4.2.jar:/Users/user/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.4.2.jar:/Users/user/.ivy2/cache/com.typesafe/ssl-config-core_2.11/bundles/ssl-config-core_2.11-0.1.3.jar:/Users/user/.ivy2/cache/com.typesafe/ssl-config-akka_2.11/bundles/ssl-config-akka_2.11-0.1.3.jar:/Users/user/.ivy2/cache/com.typesafe/config/bundles/config-1.3.0.jar:/Users/user/.ivy2/cache/com.novocode/junit-interface/jars/junit-interface-0.11.jar:/Users/user/.ivy2/cache/com.h2database/h2/jars/h2-1.4.190.jar:/Users/user/.ivy2/cache/com.google.inject.extensions/guice-assistedinject/jars/guice-assistedinject-4.0.jar:/Users/user/.ivy2/cache/com.google.inject/guice/jars/guice-4.0.jar:/Users/user/.ivy2/cache/com.google.guava/guava/bundles/guava-19.0.jar:/Users/user/.ivy2/cache/com.google.guava/guava/bundles/guava-16.0.1.jar:/Users/user/.ivy2/cache/com.google.code.gson/gson/jars/gson-2.3.1.jar:/Users/user/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-3.0.1.jar:/Users/user/.ivy2/cache/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/bundles/jackson-datatype-jsr310-2.7.1.jar:/Users/user/.ivy2/cache/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/bundles/jackson-datatype-jdk8-2.7.1.jar:/Users/user/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.7.1.jar:/Users/user/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.7.1.jar:/Users/user/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.7.1.jar:/Users/user/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.4.jar:/Users/user/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.4.jar:/Users/user/.ivy2/cache/cglib/cglib-nodep/jars/cglib-nodep-2.1_3.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 @w@/private/var/folders/c1/yrs6bpk16_v412d52ddn77qm0000gn/T/idea_working_dirs_junit.tmp @/private/var/folders/c1/yrs6bpk16_v412d52ddn77qm0000gn/T/idea_junit.tmp -socket52932
[[33mwarn] p.a.d.e.DefaultEvolutionsApi - could not create play_evolutions table
org.h2.jdbc.JdbcSQLException: Table "PLAY_EVOLUTIONS" already exists; SQL statement:

      create table play_evolutions (
          id int not null primary key,
          hash varchar(255) not null,
          applied_at timestamp not null,
          apply_script text,
          revert_script text,
          state varchar(255),
          last_problem text
      )
     [42101-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:78)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:184)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83)
	at com.zaxxer.hikari.proxy.StatementJavassistProxy.execute(StatementJavassistProxy.java)[[31merror] c.g.h.h.HtmlPage - Error loading JavaScript from [http://localhost:19001/assets/javascripts/jquery-2.2.0.min.js].
java.io.IOException: Unable to download JavaScript from 'http://localhost:19001/assets/javascripts/jquery-2.2.0.min.js' (status 404).
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1055)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:982)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:352)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:238)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:257)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:747)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:704)
	at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
	at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
[[31merror] c.g.h.h.HtmlPage - Error loading JavaScript from [http://localhost:19001/assets/javascripts/index.js].
java.io.IOException: Unable to download JavaScript from 'http://localhost:19001/assets/javascripts/index.js' (status 404).
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadJavaScriptFromUrl(HtmlPage.java:1055)
	at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:982)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:352)
	at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:238)
	at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:257)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:747)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:704)
	at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
	at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
Process finished with exit code 0
`

**Comment by werezak** [comment]
Note that this problem was also described in: [http://stackoverflow.com/questions/36141809/java-io-ioexception-unable-to-download-javascript-from-http-localhost19001](url)
