### ISSUE TITLE
Hang on code change when using play-fork-run 

### ISSUE THREAD

**Issue by avdv** [typesafehub/activator#1117]
I have the same issue described here: https://groups.google.com/forum/#!searchin/play-framework/fork/play-framework/G_4uWkJQGsY/klJhyOV-qPEJ, i.e. when using `fork in run := true` plus the play-fork-run SBT plugin, the server hangs when I change a code file and hit F5 in the browser.

I'm using Activator 1.3.10 and Play 2.5.3, play-fork-run is also version 2.5.3.

I got the following stacktrace after waiting 5 minutes:

```
[info] ! @701l6gol6 - Internal server error, for (GET) [/] ->
[info] 
[info] play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[PrivilegedActionException: null]]
[info]     at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
[info]     at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
[info]     at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:45)
[info]     at play.core.server.Server$class.getHandlerFor(Server.scala:65)
[info]     at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:47)
[info]     at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:82)
[info]     at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
[info]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
[info]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
[info]     at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
[info] Caused by: java.security.PrivilegedActionException: null
[info]     at java.security.AccessController.doPrivileged(Native Method)
[info]     at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:39)
[info]     at play.runsupport.Reloader.reload(Reloader.scala:336)
[info]     at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:118)
[info]     at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
[info]     at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[info]     at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[info]     at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
[info]     at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
[info]     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] Caused by: java.util.concurrent.TimeoutException: Futures timed out after [300000 milliseconds]
[info]     at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info]     at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info]     at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]     at scala.concurrent.Await$.result(package.scala:190)
[info]     at play.forkrun.ForkRun$$anonfun$askForReload$1.apply(ForkRun.scala:128)
[info]     at play.forkrun.ForkRun$$anonfun$askForReload$1.apply(ForkRun.scala:126)
[info]     at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:338)
[info]     at play.runsupport.Reloader$$anon$3.run(Reloader.scala:43)
[info]     at java.security.AccessController.doPrivileged(Native Method)
```

The reload at first worked twice before failing the third time around.

BTW, do I really need the play-fork-run plugin or is it's sole purpose for `activator ui`?

**Comment by iurisman** [comment]
I wonder what sense it makes to close a bug by referencing a closed bug.
