### ISSUE TITLE
Error fetching templates

### ISSUE THREAD

**Issue by alias1** [typesafehub/activator#1148]
So I was having a bunch of issues trying to use `activator new`, complaining about being unable to fetch the templates.

```
⇒  activator list-templates

Fetching the latest list of templates...


Could not fetch the updated list of templates.  Using the local cache.
Check your proxy settings or increase the timeout.  For more details see:
http://lightbend.com/activator/docs

activator.templates.repository.RepositoryException: We don't have /Users/devalias/.activator/1.3.12/templates/cache.properties with an index hash in it, even though we should have downloaded one
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:184)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Looking in that folder, it's created a `cache.properties` file, but it's empty. Then when I run it again:

```
⇒  activator list-templates

Fetching the latest list of templates...

[ERROR] [01/24/2017 15:02:02.601] [default-akka.actor.default-dispatcher-2] [ActorSystem(default)] Failed to download http://downloads.typesafe.com/typesafe-activator/index/v2/index-61c2ad1c6fe82d18d16702babd299ef458e43d37.zip: sbt.TranslatedIOException: Error opening http://downloads.typesafe.com/typesafe-activator/index/v2/index-61c2ad1c6fe82d18d16702babd299ef458e43d37.zip: java.io.IOException: Server returned HTTP response code: 503 for URL: http://downloads.typesafe.com/typesafe-activator/index/v2/index-61c2ad1c6fe82d18d16702babd299ef458e43d37.zip

[WARN] [01/24/2017 15:02:02.606] [default-akka.actor.default-dispatcher-2] [ActorSystem(default)] Failed to download new template catalog properties: activator.templates.repository.RepositoryException: Failed to download http://downloads.typesafe.com/typesafe-activator/index/v2/index-61c2ad1c6fe82d18d16702babd299ef458e43d37.zip: sbt.TranslatedIOException: Error opening http://downloads.typesafe.com/typesafe-activator/index/v2/index-61c2ad1c6fe82d18d16702babd299ef458e43d37.zip: java.io.IOException: Server returned HTTP response code: 503 for URL: http://downloads.typesafe.com/typesafe-activator/index/v2/index-61c2ad1c6fe82d18d16702babd299ef458e43d37.zip

[ERROR] [01/24/2017 15:02:02.608] [default-akka.actor.default-dispatcher-2] [akka://default/user/template-cache] Could not find a template catalog. (activator.templates.repository.RepositoryException: We don't have /Users/devalias/.activator/1.3.12/templates/cache.properties with an index hash in it, even though we should have downloaded one
activator.templates.repository.RepositoryException: We don't have /Users/devalias/.activator/1.3.12/templates/cache.properties with an index hash in it, even though we should have downloaded one
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:184)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

activator.templates.repository.RepositoryException: We don't have /Users/devalias/.activator/1.3.12/templates/cache.properties with an index hash in it, even though we should have downloaded one
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:184)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I believe the 503's are from a proxy here at work (stopping binary file download), but even when I route through a VPN, i'm having seemingly non-deterministic errors with this..

So I tried manually manually downloading the cache file with `wget` (can't remember the URL off hand at the moment.. but I managed to trigger a different error message I didn't save), at which point I get this error.

```
⇒  activator list-templates

Fetching the latest list of templates...

[INFO] [01/24/2017 14:55:23.571] [default-akka.actor.default-dispatcher-6] [akka://default/user/template-cache] We have index hash 61c2ad1c6fe82d18d16702babd299ef458e43d37 but haven't downloaded that index - attempting to download it now.

Could not fetch the updated list of templates.  Using the local cache.
Check your proxy settings or increase the timeout.  For more details see:
http://lightbend.com/activator/docs

[INFO] [01/24/2017 14:55:45.826] [fallback-akka.actor.default-dispatcher-5] [akka://fallback/user/template-cache] We have index hash 61c2ad1c6fe82d18d16702babd299ef458e43d37 but haven't downloaded that index - attempting to download it now.
[ERROR] [01/24/2017 14:55:45.828] [fallback-akka.actor.default-dispatcher-5] [akka://fallback/user/template-cache] Could not find a template catalog. (java.lang.RuntimeException: Offline mode! Cannot resolve new index.
java.lang.RuntimeException: Offline mode! Cannot resolve new index.
	at scala.sys.package$.error(package.scala:27)
	at activator.cache.DefaultTemplateCache$defaultRemoteRepo$.resolveIndexTo(DefaultTemplateCache.scala:85)
	at activator.cache.TemplateCacheActor$$anonfun$9.apply(TemplateCacheActor.scala:165)
	at activator.cache.TemplateCacheActor$$anonfun$9.apply(TemplateCacheActor.scala:163)
	at scala.Option.foreach(Option.scala:257)
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:163)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

java.lang.RuntimeException: Offline mode! Cannot resolve new index.
	at scala.sys.package$.error(package.scala:27)
	at activator.cache.DefaultTemplateCache$defaultRemoteRepo$.resolveIndexTo(DefaultTemplateCache.scala:85)
	at activator.cache.TemplateCacheActor$$anonfun$9.apply(TemplateCacheActor.scala:165)
	at activator.cache.TemplateCacheActor$$anonfun$9.apply(TemplateCacheActor.scala:163)
	at scala.Option.foreach(Option.scala:257)
	at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:163)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

So I guess i'm wondering if you've ever seen something like this before, if there are any debug flags/etc I could be using to dig in deeper, etc. Thanks!

**Comment by alias1** [comment]
Hrmm.. so I tried doing this through a different VPN today and it had no issues.. so probably just a local error.
