### ISSUE TITLE
Javax Persistence dependency not found

### ISSUE THREAD

**Issue by dnyaneshwarjadhav** [typesafehub/activator#1156]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading global plugins from C:\Users\samarth\.sbt\0.13\plugins
[info] Loading project definition from C:\Users\samarth\git\learning-play-framework\project
[info] Set current project to LunchIn (in build file:/C:/Users/samarth/git/learning-play-framework/)
[info] About to create Eclipse project files for your project(s).
[info] Updating {file:/C:/Users/samarth/git/learning-play-framework/}root...
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/com/google/guava/guava-parent/18.0/guava-parent-18.0.jar
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/com/impetus/kundera-parent/2.9/kundera-parent-2.9.jar
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/com/impetus/kundera/2.9/kundera-2.9.jar
[info] Resolving javax.persistence#persistence-api;2.0 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn]  module not found: javax.persistence#persistence-api;2.0
[warn] ==== local: tried
[warn]   C:\Users\samarth\.ivy2\local\javax.persistence\persistence-api\2.0\ivys\ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\samarth\.sbt\preloaded\javax.persistence\persistence-api\2.0\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/samarth/.sbt/preloaded/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== Kundera: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== Riptano: tried
[warn]   http://mvn.riptano.com/content/repositories/public/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== Kundera missing: tried
[warn]   http://kundera.googlecode.com/svn/maven2/maven-missing-resources/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== Scale 7: tried
[warn]   https://github.com/s7/mvnrepo/raw/master/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[info] Resolving org.apache#apache;13 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/lucene/lucene-solr-grandparent/4.4.0/lucene-solr-grandparent-4.4.0.jar
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/lucene/lucene-parent/4.4.0/lucene-parent-4.4.0.jar
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/fluentlenium/fluentlenium-parent/0.10.3/fluentlenium-parent-0.10.3.jar
[info] Resolving org.apache.httpcomponents#project;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/httpcomponents/httpcomponents-client/4.3.4/httpcomponents-client-4.3.4.jar
[info] Resolving org.apache.httpcomponents#project;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/httpcomponents/httpcomponents-core/4.3.2/httpcomponents-core-4.3.2.jar
[info] Resolving org.apache.httpcomponents#project;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/httpcomponents/httpcomponents-client/4.3.3/httpcomponents-client-4.3.3.jar
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://repo1.maven.org/maven2/com/typesafe/play/play-java-jdbc_2.11/2.4.2/play-java-jdbc_2.11-2.4.2.jar ...
[info]  [SUCCESSFUL ] com.typesafe.play#play-java-jdbc_2.11;2.4.2!play-java-jdbc_2.11.jar (583ms)
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: javax.persistence#persistence-api;2.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          javax.persistence:persistence-api:2.0
[warn]            +- com.impetus.core:kundera-core:2.9
[warn]            +- com.impetus.client:kundera-mongo:2.9 (C:\Users\samarth\git\learning-play-framework\build.sbt#L11-23)
[warn]            +- lunchin:lunchin_2.11:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: javax.persistence#persistence-api;2.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:165)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: javax.persistence#persistence-api;2.0: not found
[info] Updating {file:/C:/Users/samarth/git/learning-play-framework/}root...
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/com/google/guava/guava-parent/18.0/guava-parent-18.0.jar
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/com/impetus/kundera-parent/2.9/kundera-parent-2.9.jar
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/com/impetus/kundera/2.9/kundera-2.9.jar
[info] Resolving javax.persistence#persistence-api;2.0 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn]  module not found: javax.persistence#persistence-api;2.0
[warn] ==== local: tried
[warn]   C:\Users\samarth\.ivy2\local\javax.persistence\persistence-api\2.0\ivys\ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\samarth\.sbt\preloaded\javax.persistence\persistence-api\2.0\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/samarth/.sbt/preloaded/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== Kundera: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== Riptano: tried
[warn]   http://mvn.riptano.com/content/repositories/public/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== Kundera missing: tried
[warn]   http://kundera.googlecode.com/svn/maven2/maven-missing-resources/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[warn] ==== Scale 7: tried
[warn]   https://github.com/s7/mvnrepo/raw/master/javax/persistence/persistence-api/2.0/persistence-api-2.0.pom
[info] Resolving org.apache#apache;13 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/lucene/lucene-solr-grandparent/4.4.0/lucene-solr-grandparent-4.4.0.jar
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/lucene/lucene-parent/4.4.0/lucene-parent-4.4.0.jar
[info] Resolving org.sonatype.oss#oss-parent;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/fluentlenium/fluentlenium-parent/0.10.3/fluentlenium-parent-0.10.3.jar
[info] Resolving org.apache.httpcomponents#project;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/httpcomponents/httpcomponents-client/4.3.4/httpcomponents-client-4.3.4.jar
[info] Resolving org.apache.httpcomponents#project;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/httpcomponents/httpcomponents-core/4.3.2/httpcomponents-core-4.3.2.jar
[info] Resolving org.apache.httpcomponents#project;7 ...
[error] SERVER ERROR: Service Temporarily Unavailable url=http://mvn.riptano.com/content/repositories/public/org/apache/httpcomponents/httpcomponents-client/4.3.3/httpcomponents-client-4.3.3.jar
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: javax.persistence#persistence-api;2.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          javax.persistence:persistence-api:2.0
[warn]            +- com.impetus.core:kundera-core:2.9
[warn]            +- com.impetus.client:kundera-mongo:2.9 (C:\Users\samarth\git\learning-play-framework\build.sbt#L11-23)
[warn]            +- lunchin:lunchin_2.11:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: javax.persistence#persistence-api;2.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:127)
        at sbt.IvySbt.withIvy(Ivy.scala:124)
        at sbt.IvySbt$Module.withModule(Ivy.scala:155)
        at sbt.IvyActions$.updateEither(IvyActions.scala:165)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: javax.persistence#persistence-api;2.0: not found
[error] Could not create Eclipse project files:
[error] Error evaluating task 'scalacOptions': error
[error] Error evaluating task 'externalDependencyClasspath': error

**Comment by dnyaneshwarjadhav** [comment]
my environment is as below 
Java : 1.8
Scala : 2.11
sbt : 0.13.8
