### ISSUE TITLE
Activator new fails with IllegalArgumentException

### ISSUE THREAD

**Issue by greenrd** [typesafehub/activator#737]
Steps to reproduce:

    activator.bat
    activator.bat new

Output:

Fetching the latest list of templates...

[WARN] [09/28/2014 06:16:04.309] [default-akka.actor.default-dispatcher-3] [Acto
rSystem(default)] Failed to download new template catalog properties: java.lang.
IllegalArgumentException: requirement failed: Source file 'C:\Users\green_000\.a
ctivator\1.2.10\templates\index.db_74b88fd4b25b9250.tmp' is a directory.
[ERROR] [09/28/2014 06:16:04.314] [default-akka.actor.default-dispatcher-3] [akk
a://default/user/template-cache] Could not find a template catalog. (activator.t
emplates.repository.RepositoryException: We don't have C:\Users\green_000\.activ
ator\1.2.10\templates\cache.properties with an index hash in it, even though we
should have downloaded one
activator.templates.repository.RepositoryException: We don't have C:\Users\green
_000\.activator\1.2.10\templates\cache.properties with an index hash in it, even
 though we should have downloaded one
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:
184)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.
scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
ractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)

**Comment by henrikengstrom** [comment]
Closing this now. Please try downloading the latest version of Activator if this issue still persists.
