### ISSUE TITLE
NPE in `activator ui` in case of failing test

### ISSUE THREAD

**Issue by g7r** [typesafehub/activator#780]
WTR:
1. `> activator new test-npe play-java`
2. `> vim test-npe/test/IntegrationTest.java` (add `org.junit.Assert.fail();` as first line of `IntegrationTest.test()`)
3. `> activator ui`
4. Select application `test-npe` and run tests

In compile output we'll see:

```
  Exception in thread "Thread-5" java.lang.NullPointerException
  at scala.util.parsing.json.JSONFormat$$anonfun$1.apply(Parser.scala:59)
  at scala.util.parsing.json.JSONFormat$$anonfun$1.apply(Parser.scala:55)
  at scala.util.parsing.json.JSONObject$$anonfun$toString$1.apply(Parser.scala:96)
  at scala.util.parsing.json.JSONObject$$anonfun$toString$1.apply(Parser.scala:96)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
  at scala.collection.immutable.Map$Map3.foreach(Map.scala:154)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
  at scala.collection.AbstractTraversable.map(Traversable.scala:105)
  at scala.util.parsing.json.JSONObject.toString(Parser.scala:96)
  at scala.util.parsing.json.JSONType.toString(Parser.scala:33)
  at com.typesafe.sbtrc.protocol.Message$.paramsToJsonString(Protocol.scala:384)
  at com.typesafe.sbtrc.controller.ParamsHelper$.fromMap(UI.scala:18)
  at com.typesafe.sbtrc.controller.UiTestListener.com$typesafe$sbtrc$controller$UiTestListener$$sendEvent(UiTestListener.scala:51)
  at com.typesafe.sbtrc.controller.UiTestListener$$anonfun$testEvent$1.apply(UiTestListener.scala:42)
  at com.typesafe.sbtrc.controller.UiTestListener$$anonfun$testEvent$1.apply(UiTestListener.scala:25)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
  at com.typesafe.sbtrc.controller.UiTestListener.testEvent(UiTestListener.scala:25)
  at sbt.React$$anonfun$react$7.apply(ForkTests.scala:127)
  at sbt.React$$anonfun$react$7.apply(ForkTests.scala:127)
  at scala.collection.immutable.List.foreach(List.scala:318)
  at sbt.React.react(ForkTests.scala:127)
  at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:76)
  at java.lang.Thread.run(Thread.java:745)
  Internal error when running tests: sbt.ForkMain$Run$RunAborted: java.net.SocketException: Broken pipe
```

Everything is OK if I run `activator test` from shell. So I believe this issue belongs to UI.

**Comment by henrikengstrom** [comment]
Just tried this with Activator 1.3.2 and things seem to work without any NPE. Closing this issue.
Thanks for using Activator.
