### ISSUE TITLE
Activator 1.2.12 - NoClassDefFoundError

### ISSUE THREAD

**Issue by PBastiani** [typesafehub/activator#813]
From the MS-DOS Console, several activator commands fail with this exception : 

java.lang.NoClassDefFoundError: activator/UICacheHelper$
        at activator.ActivatorCli$$anonfun$apply$1.apply$mcI$sp(ActivatorCli.scala:21)
        at activator.ActivatorCli$$anonfun$apply$1.apply(ActivatorCli.scala:19)
        at activator.ActivatorCli$$anonfun$apply$1.apply(ActivatorCli.scala:19)
        at activator.ActivatorCli$.withContextClassloader(ActivatorCli.scala:179)
        at activator.ActivatorCli$.apply(ActivatorCli.scala:19)
        at activator.ActivatorLauncher.run(ActivatorLauncher.scala:35)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:19)
        at xsbt.boot.Boot$.runImpl(Boot.scala:44)
        at xsbt.boot.Boot$.main(Boot.scala:20)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: activator.UICacheHelper$
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 15 more
Error during sbt execution: java.lang.NoClassDefFoundError: activator/UICacheHelper$

Repeatable 
- with 'new' & 'list-templates'  as parameter
- with or without the ~/.activator folder
- with the online & the offline distributions.

Note :The UI option works like a charm...

**Comment by henrikengstrom** [comment]
Hi @PBastiani 
Is this still an issue for you or can we close the ticket?

**Comment by PBastiani** [comment]
The workaround solves the problem !

I suspect a problem when downloading one of the jars !
