### ISSUE TITLE
Error  java.lang.RuntimeException: Setting value cannot be null: {file:/D:/typesafe/activator-master/}/*:gitCurrentBranch

### ISSUE THREAD

**Issue by arnoldangel** [typesafehub/activator#985]
All I did was execute sbt in the D:\typesafe\activator-master directory.  What happened?

[debug]   :: sorted deduced result: List(sbt.plugins.CorePlugin, sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.JUnitXmlReportPlugin)
[debug] [Loading] Done in D:\typesafe\activator-master, returning: (echo-cotests-collect, echo-cotests-common210, echo-cotests-common211, echo-cotests-trace2-akka22, echo-cotests-trace2-akka23-scala21
0, echo-cotests-trace2-akka23-scala211, echo-cotests-trace-akka22, echo-cotests-trace-akka23-scala210, echo-cotests-trace-akka23-scala211, echo-cotests-trace-play23-scala210, echo-cotests-trace-play23
-scala211, echo-cotests-trace-play-common23-scala210, echo-cotests-trace-play-common23-scala211, echo, echo-cotests, echo-sigar-libs, echo-trace, echo-collect, echo-collect211, echo-event210-protobuf2
4, echo-event210-protobuf25, echo-event211-protobuf24, echo-event211-protobuf25, echo-trace-protocol-protobuf24, echo-trace-protocol-protobuf25, echo-trace210-protobuf24, echo-trace210-protobuf25, ech
o-trace211-protobuf24, echo-trace211-protobuf25, echo-trace-akka22, echo-trace-akka23-scala210, echo-trace-akka23-scala211, echo-trace-play23-scala210, echo-trace-play23-scala211, echo-trace-play-comm
on, echo-trace-scala210-protobuf24, echo-trace-scala210-protobuf25, echo-trace-scala211-protobuf24, echo-trace-scala211-protobuf25, activator-dist, activator-dontuseme, activator-integration-tests, ac
tivator-launcher, template-repository, news, activator-offline-tests, activator-props, root, activator-ui, activator-ui-common, sbt-echo, sbt-echo-akka, sbt-echo-play)
java.lang.RuntimeException: Setting value cannot be null: {file:/D:/typesafe/activator-master/}/*:gitCurrentBranch
        at scala.sys.package$.error(package.scala:27)
        at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] Setting value cannot be null: {file:/D:/typesafe/activator-master/}/*:gitCurrentBranch
[error] Use 'last' for the full log.
[debug] > load-failed
[debug] > last
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by arnoldangel** [comment]
D:\typesafe\activator-master>sbt "activator-ui/run"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading project definition from D:\typesafe\activator-master\project\project
[info] Loading project definition from D:\typesafe\activator-master\project
java.lang.RuntimeException: Setting value cannot be null: {file:/D:/typesafe/activator-master/}/*:gitCurrentBranch
        at scala.sys.package$.error(package.scala:27)
        at sbt.EvaluateSettings$INode.setValue(INode.scala:143)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] Setting value cannot be null: {file:/D:/typesafe/activator-master/}/*:gitCurrentBranch
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by havocp** [comment]
looks like sbt-git is exploding because it doesn't find a current git branch. is this a git clone? @jsuereth may have ideas.

**Comment by arnoldangel** [comment]
I did not clone. I just downloaded the zip, installed sbt, then tried to run some commands.  I am giving up for now. cannot seem to overcome the typesafe acitivator issues. Thanks for the response.

**Comment by havocp** [comment]
it looks like you had the activator source code zip, for what it's worth. I'm not sure that's what you intended; if so, you'd probably want to clone the source from git. If you wanted the actual activator app, that's at https://typesafe.com/getstarted

**Comment by havocp** [comment]
make that https://typesafe.com/get-started

**Comment by matanster** [comment]
Might it have been https://github.com/sbt/sbt-git/issues/97?
