### ISSUE TITLE
Activator does not work with remote repositories and with UI

### ISSUE THREAD

**Issue by rojaster** [typesafehub/activator#996]
When i created a project with "activator new blabla java-play" my activator tries to fetch and updates my local templates and that's what i see:

<pre>
Fetching the latest list of templates...

ряЁ 03, 2015 3:13:04 PM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.jav
:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:
04)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository
scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepositor
.scala:238)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRe
oteTemplateRepository.scala:192)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRe
oteTemplateRepository.scala:190)
        at sbt.IO$.withTemporaryDirectory(IO.scala:291)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepos
tory.scala:190)
        at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.
cala:184)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

ряЁ 03, 2015 3:13:10 PM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.jav
:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:
04)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository
scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepositor
.scala:238)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRe
oteTemplateRepository.scala:192)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRe
oteTemplateRepository.scala:190)
        at sbt.IO$.withTemporaryDirectory(IO.scala:291)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepos
tory.scala:190)
        at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.
cala:184)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

ряЁ 03, 2015 3:13:16 PM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.jav
:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:
04)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository
scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepositor
.scala:238)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRe
oteTemplateRepository.scala:192)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRe
oteTemplateRepository.scala:190)
        at sbt.IO$.withTemporaryDirectory(IO.scala:291)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepos
tory.scala:190)
        at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.
cala:184)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

ряЁ 03, 2015 3:13:23 PM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out
org.apache.http.conn.ConnectTimeoutException: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:376)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.jav
:148)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:280)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:165)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2951)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:885)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:941)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadFromS3(UriRemoteTemplateRepository.scala:
04)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadTryingS3First(UriRemoteTemplateRepository
scala:135)
        at activator.templates.repository.UriRemoteTemplateRepository.resolveIndexProperties(UriRemoteTemplateRepositor
.scala:238)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRe
oteTemplateRepository.scala:192)
        at activator.templates.repository.UriRemoteTemplateRepository$$anonfun$downloadNewIndexProperties$1.apply(UriRe
oteTemplateRepository.scala:190)
        at sbt.IO$.withTemporaryDirectory(IO.scala:291)
        at activator.templates.repository.UriRemoteTemplateRepository.downloadNewIndexProperties(UriRemoteTemplateRepos
tory.scala:190)
        at activator.templates.repository.UriRemoteTemplateRepository.ifNewIndexProperties(UriRemoteTemplateRepository.
cala:184)
        at activator.cache.TemplateCacheActor.preStart(TemplateCacheActor.scala:149)
        at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
        at activator.cache.TemplateCacheActor.aroundPreStart(TemplateCacheActor.scala:25)
        at akka.actor.ActorCell.create(ActorCell.scala:580)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[WARN] [04/03/2015 15:13:23.718] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Failed to grab s3 buc
et, attempting to use http to 'http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties'. (Failed t
 download http://downloads.typesafe.com/typesafe-activator/index/v2/current.properties from s3: com.amazonaws.AmazonCli
ntException: Unable to execute HTTP request: Connect to s3.amazonaws.com/s3.amazonaws.com/54.231.17.32 timed out)

Could not fetch the updated list of templates.  Using the local cache.
Check your proxy settings or increase the timeout.  For more details see:
http://typesafe.com/activator/docs

OK, application "my-first-app" is being created using the "play-java" template.

[ERROR] [04/03/2015 15:13:44.814] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Failed to download h
tp://downloads.typesafe.com/typesafe-activator/index/v2/current.properties: sbt.TranslatedIOException: Error opening ht
p://downloads.typesafe.com/typesafe-activator/index/v2/current.properties: java.net.ConnectException: Connection timed
ut: connect
[WARN] [04/03/2015 15:13:44.816] [default-akka.actor.default-dispatcher-3] [ActorSystem(default)] Failed to download ne
 template catalog properties: activator.templates.repository.RepositoryException: Failed to download http://downloads.t
pesafe.com/typesafe-activator/index/v2/current.properties: sbt.TranslatedIOException: Error opening http://downloads.ty
esafe.com/typesafe-activator/index/v2/current.properties: java.net.ConnectException: Connection timed out: connect
To run "my-first-app" from the command line, "cd my-first-app" then:
H:\D_backup\My_works\java\projects\java_play\my-first-app/activator run

To run the test for "my-first-app" from the command line, "cd my-first-app" then:
H:\D_backup\My_works\java\projects\java_play\my-first-app/activator test

To run the Activator UI for "my-first-app" from the command line, "cd my-first-app" then:
H:\D_backup\My_works\java\projects\java_play\my-first-app/activator ui

java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:116)
        at activator.ActivatorCli$.activator$ActivatorCli$$generateProjectTemplate(ActivatorCli.scala:147)
        at activator.ActivatorCli$$anonfun$apply$1$$anonfun$13$$anonfun$apply$3.apply(ActivatorCli.scala:105)
        at activator.ActivatorCli$$anonfun$apply$1$$anonfun$13$$anonfun$apply$3.apply(ActivatorCli.scala:104)
        at scala.Option.map(Option.scala:146)
        at activator.ActivatorCli$$anonfun$apply$1$$anonfun$13.apply(ActivatorCli.scala:104)
        at activator.ActivatorCli$$anonfun$apply$1$$anonfun$13.apply(ActivatorCli.scala:103)
        at scala.Option.flatMap(Option.scala:171)
        at activator.ActivatorCli$$anonfun$apply$1.apply$mcI$sp(ActivatorCli.scala:103)
        at activator.ActivatorCli$$anonfun$apply$1.apply(ActivatorCli.scala:19)
        at activator.ActivatorCli$$anonfun$apply$1.apply(ActivatorCli.scala:19)
        at activator.ActivatorCli$.withContextClassloader(ActivatorCli.scala:179)
        at activator.ActivatorCli$.apply(ActivatorCli.scala:19)
        at activator.ActivatorLauncher.run(ActivatorLauncher.scala:37)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
</pre>

After this i tried activate ui with "activator ui"  and something wrong. By default "http://localhost:8888" host isn't working and i'm trying to redefine standard port by parameter "-Dhttp.port=...", but all my efforts is a trash.

Look at : https://yadi.sk/i/DxJszHVAfj4u6

any ideas?

My system is windows7Ultimate with java8 by default and java7 ?

**Comment by jsuereth** [comment]
Hello @rojaster.  Sorry no one got to this beforehand.  It looks like you're seeing a proxy-download error with windows.  Are you sure your activator is configured for proxy usage?
